### ISSUE TITLE
OIDC example fails

### ISSUE THREAD

**Issue by edzis** [AzureAD/passport-azure-ad#137]
Using the default v2 config on top of #136 I get the following error.

> The provided value for the input parameter 'redirect_uri' is not valid. The expected value is 'https://login.live.com/oauth20_desktop.srf' or a URL which matches the redirect URI registered for this client application.

When I use my clientID `c9655d1d-f356-46a7-afe1-431c0d6eeb37` I get runtime error:
> Error: No email found
>   at Strategy._verify (/Users/***/app/passport-azure-ad/examples/login-oidc/app.js:120:19)

```
{ id: 'AAAAAAAAAAAAAAAAAAAAALEvgXFVahfRQnMLE87e9Wk',
  displayName: undefined,
  name:
   { familyName: undefined,
     givenName: undefined,
     middleName: undefined },
  email: undefined,
  _raw: '...',
  _json:
   { ver: '2.0',
     iss: 'https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0',
     aud: '86b5ce72-0a83-44ac-abf3-626f7ec2cb30',
     exp: 1467274953,
     iat: 1467188553,
     nonce: 'IcFvMjaJNsHmjPch',
     sub: 'AAAAAAAAAAAAAAAAAAAAALEvgXFVahfRQnMLE87e9Wk',
     tid: '9188040d-6c67-4c5b-b112-36a304b66dad' } }
```

**Comment by edzis** [comment]
Nothing changes even if I change the signature of the verify function to `function(iss, sub, profile, accessToken, refreshToken, done)` or add `scope: ['email', 'profile']`.

**Comment by polita** [comment]
@edzis We're having a hard time reproing this issue. Are you using a Microsoft (Hotmail.com, live.com, msn.com, etc.) account or an Azure AD account? 

Dev team: We need to load the profile for whatever endpoint is being used here to pass back through Passport.

**Comment by edzis** [comment]
I have been testing this with my MS account that uses email address from our own domain.

**Comment by polita** [comment]
@edzis- is this account an AAD account?

**Comment by edzis** [comment]
No, it was created as a LiveID account.

**Comment by lovemaths** [comment]
@edzis I am assuming you are using the login-oidc example, with the client_config_v2 config file. Please let me know if the following can solve your issue:

1. in order to use v2 endpoint, the app must be registered at: https://apps.dev.microsoft.com
from there you will can get application id, create application secret (be sure to save it somewhere), and make sure in the 'platform' section, choose your platform and add the following return url: "http://localhost:3000/auth/openid/return"

2. in your client_config_v2.js
(1) use "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration" as your identityMetadata
(2) use the application id, application secret for your clientID, clientSecret fields
(3) make sure you have: "scope: ['email', 'profile']" uncommented

3. in your app.js
(1) in "passport.use(new OIDCStrategy({
                          callbackURL: config.creds.returnURL,
                          scope: config.creds.scope,     <================== add this line
                          ..................................
          }, ...."

The example works after I use the setting above, please let me know if it doesn't work for you.

**Comment by edzis** [comment]
@lovemaths this works for me, thanks.
Is there a reason why these changes are not applied already in the code? Is there another usecase that the default configuration covers?

**Comment by lovemaths** [comment]
@edzis The example needs more details on the instructions. 
(1) The "scope: config.creds.scope" line should be always added to your app.js.
(2) passport uses 'openid' as the scope by default, if you need more permissions, then you need to uncomment the 'scope' in config.js and add the additional permissions into 'scope', for example, 'email', 'profile' etc. There is no need to add 'openid' since passport adds it automatically. 
(3) The default setting for v1 and v2 are different.
(3.1) For v1, application is registered at AAD; for v2, application is registered at 'https://apps.dev.microsoft.com'
(3.2) For v1, use "https://login.microsoftonline.com/<your_tenant_name_or_id>/.well-known/openid-configuration" as the metadata; for v2, use "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration" as the metadata.
(3.3) For v1, you don't really need the 'scope' in config.js for the example, since the id_token returned from v1 has a rich content, which normally contains the 'email' claim (you might need to add more permissions to the 'scope' in config.js if you want more permissions); for v2, the id_token returned has a limited content, which doesn't contain 'email' claim by default, you need to specify more permissions like 'email', 'profile' in 'scope' in config.js
