### ISSUE TITLE
Profile Data Not Loading

### ISSUE THREAD

**Issue by securityvoid** [AzureAD/passport-azure-ad#232]
I've been attempting to get the azuread-oidc strategy working today and have run into a number of issues even getting it running. It seems that a number of things have changed and documentation has not been updated.

In any case, the last (and hopefully final) issue I've run into is that the profile does not appear to populate with the email, givenName, lastName, etc. (See the screenshot):
![profile_not_loaded](https://cloud.githubusercontent.com/assets/10822557/19402823/64b2f57e-9231-11e6-9178-4516ee4e83b2.png)

This is the case regardless of if I set the scope to "openid", "profile", or "email". In case it matters, my latest code is below, but I believe the "profile" should really automatically be populated by passport:
```
passport.use(new OIDCStrategy({
      callbackURL: ((config.secure && config.secure.ssl === true) ? "https" : "http") + "://" + config.domain + ":" + config.port + config['azuread-openidconnect'].callbackURL,
      clientID: config['azuread-openidconnect'].clientID,
      clientSecret: config['azuread-openidconnect'].clientSecret,
      identityMetadata: 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration',
      responseType: 'id_token',
      responseMode: 'form_post',
      validateIssuer: false,
      redirectUrl: ((config.secure && config.secure.ssl === true) ? "https" : "http") + "://" + config.domain + ":" + config.port + config['azuread-openidconnect'].callbackURL,
      allowHttpForRedirectUrl: (config.secure && config.secure.ssl === true) ? false : true,
      scope: ['openid']
      },
      function(iss, sub, profile, accessToken, refreshToken, done) {
        console.log(JSON.stringify(profile));
        console.log('Example: Email address we received was: ', profile.email);
        var lastName = profile.displayName.split(/ +/).pop().trim();
        var firstName = profile.displayName.substr(0, profile.displayName.lastIndexof(lastName));
        // Create the user OAuth profile
        var providerUserProfile = {
          firstName: firstName,
          lastName: lastName,
          displayName: profile.displayName,
          email: profile.emails ? profile.emails[0].value : undefined,
          username: profile.username || generateUsername(profile),
          profileImageURL: (profile.id) ? '//graph.facebook.com/' + profile.id + '/picture?type=large' : undefined,
          provider: 'facebook',
          providerIdentifierField: 'id',
          providerData: providerData
        };

        // Save the user OAuth profile
        users.saveOAuthUserProfile(req, providerUserProfile, done);


      }
  ));

```
It is also worth noting that I originally tried to setup an application within Portal.Azure.com -> Azure AD -> App Registrations. I also tried setting up an application in the equivalent under the Classic portal. Both of these gave me the error, "is not supported for this API version". It was only when I created the application at apps.dev.microsoft.com that everything appeared to work (minus loading the profile).

**Comment by lovemaths** [comment]
@securityvoid  We released 3.0.0 yesterday with breaking changes. It seems to me you are using the old sample with the new version of passport-azure-ad. Please refer to the changelog in master branch for the changes, and refer to the [latest sample](https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs)

Since you are using v2 endpoint, the app must be registered at apps.dev.microsoft.com.

The _json field in profile is all the claims contained in id_token.  We just select some fields from _json and make a profile. When you use `profile` scope, you can only get a `name` claim; when you use `email` scope, you will get an `email` claim if it exists. This is why you don't get the `email`, `givenName` etc. Please refer to the following page for what claims you can get from v2 endpoint:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-tokens/

Please reopen this issue if it is still not working for you. Thanks.

**Comment by securityvoid** [comment]
@lovemaths profile.email is not populated even though I define the scope as any combination of 'openid', 'profile', 'email'. 

E-mail definitely exists. I'm using this against an O365 user-account where Azure AD is the back-end for everything.

Also, what in my example makes you think I'm using an old sample currently? Can you point out what is wrong? The example you pointed me to is one of several examples I've been working from today.

**Comment by securityvoid** [comment]
@lovemaths BTW, github does not allow the re-opening of the issue if a repo-collaborator closed it. I can only re-open an issue if I opened it.

**Comment by lovemaths** [comment]
@securityvoid

There are a couple of reasons why I think you are using the old sample: 
(1) new sample doesn't use `profile.email` anywhere, since passport-azure-ad version 3.0.0 no longer has that field. The new sample uses `profile.oid` anywhere `profile.email` was used in the old sample.
(2) new sample doesn't use `callbackURL` in the constructor of strategy, since that one is renamed to `redirectURL`.
It seems to me you are modifying the old sample. I updated the sample in that URL yesterday afternoon around 3pm.
   
About the `email` claim. If you really need the `email` claim, you should go to `profile._json`, check if it is there. `profile._json` is all the claims in id_token. Even if you have email in your account and you use the `email` scope, you may not receive an `email` claim in id_token. 
If you just want to use `email` claim to serialize/deserialize user, then you should use `profile.oid` instead. This is the main reason why we switched to `profile.oid` from `profile.email` to serialize and deserialize users in 3.0.0.

**Comment by securityvoid** [comment]
I really don't understand. Part of the goal's of using something like passport is for all of this stuff to be standardized so that if there is an e-mail present, it is put in the same spot. Likewise with the givenName and familyName fields. Why would I go to _json and manually parse it? Shouldn't the passport module perform according to the [Passport docs](http://passportjs.org/docs/profile)?

Likewise, when you're doing OIDC (Based on Oauth 2.0), why change CallbackURL to RedirectUrl?

Facebook, Github, Paypal and Twitter all have Passport modules and all of them seem to follow these standards. 

Yes, its possible to work with Microsoft's module if its different, but why make it different? All it does is make it so people have to spend more time looking for the most current documentation since things are changing, rather than finding ANY example of any of the common ones and get it working.

**Comment by lovemaths** [comment]
@securityvoid 

`profile._json` is an object, you don't need to parse anything. All the claims in id_token are in `profile._json`. If you have `email` claim in id_token, you can use `profile._json.email` to get it. Here is a list of claims you may get from v2 endpoint (https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-tokens/). Azure AD v2 doesn't support givenName and familyName.

**Comment by bencooper222** [comment]
This issue is dead but I'm running into this same issue and it's ridiculous. Why does AzureAD feel like it should defy known Passport idioms? It completely defeats the point of Passport. I'd offer to PR to fix this but I'd guess it won't be accepted.

**Comment by SvemirskiHod** [comment]
Microsoft complicating things? News to me...

**Comment by SvemirskiHod** [comment]
What's more, is that I've had cases where the email was not included in `profile._json.email`. It was instead under `profile._json.preferred_username`. You can guess how pleased I was when I realized this.

**Comment by bencooper222** [comment]
Yeah, it's literally insane. Kudos to MSFT for actually maintaining their passport strategy but jfc, the sheer contempt for developers by having the nerve to make a `_json: any` object is out of this world.

**Comment by macduy** [comment]
Thanks @SvemirskiHod, `profile._json.preferred_username` helped in my case.
