### ISSUE TITLE
Example for connecting to a private ADFS

### ISSUE THREAD

**Issue by ambahk** [AzureAD/passport-azure-ad#25]
Is there any examples on connecting to a private ADFS by exchanging metadata?  In particular, how should I prepare the metadata data for the IdP?  Thanks?

I see that in saml.js there's SAML.prototype.identity().  Maybe I should fill in all the options there to generate the metadata.xml?  But then, is this necessary if we are based on wsfed?

Thank you!

**Comment by OwenBrotherwood** [comment]
@ambahk I am working my way thru a wsfed for private ADFS.
One think was that the example was not https : done and I describe a quick method to obtain a pfx certificate.
Current result https works but no joy yet

https://github.com/OwenBrotherwood/passport-azure-ad/tree/master/examples/login-wsfed

**Comment by ambahk** [comment]
Thanks for your reply Owen.  My IdP client has decided to setup the trust on their AD manually.  We are still in the process.  From your experience is this a viable route?  Thanks.

**Comment by ambahk** [comment]
Oh sorry I forgot to mention.  We have switched to saml2 instead of wsfed because the client wants to use SAML Tracer (the Firefox extension) to check the SAML messages.  So I guess my previous comment is irrelevant.

**Comment by OwenBrotherwood** [comment]
Status.
The Microsoft System Staff have a MS ADFS for internal SSO and have successfully used the service for Microsoft Centric needs. 
However, at the present moment, the passport node way is not working.
At the present time, a redirect is created to:
https:<MS ADFS server>/<path>/2005
https://<MS ADFS server>/<path>/2005/certificatemixed?wtrealm=https%3A%2F%2F<realm details%2F&wa=wsignin1.0&whr=

MS Explorer: returns to /login and a blank page
Firefox: "hangs" on the MS ADFS url : get returns a 400 bad request

**Comment by brandwe** [comment]
This is interesting. I don't think we ever anticipated the Passport lib being used in this way. I'll take some research with @RandalliLama and get back to you.

**Comment by OwenBrotherwood** [comment]
@brandwe We are ready when you are: our current thoughts are that the certificatemixed is not the method needed. I am getting a history update from our MS staff on what was done before the introduction of the identityMetadata xml file. Apparently, the xml file creates a quicker/easier config but then one has to ensure one uses the correct item that is the correct "certificatemixed" or what should be used instead of this.

**Comment by OwenBrotherwood** [comment]
It seems that if an identityMetadata is defined, certificatemixed may be hardcoded.
If one uses a cert instead of identityMetadata, then the otherwise ignored identityProviderUrl is used.
If the identityProviderUrl is a usernamemixed, it may be possible to obtain a authentication

**Comment by OwenBrotherwood** [comment]
Compare with the "normal way" that AD is sometimes interfaced to by non-MS components that I have experienced.
- The server component uses LDAP, and in the case of anonymous bind not being allowed, the server component has to Bind with credentials.
- The user identifies themselves: username and password
- The credentials are checked by the server component and the appropriate flow continues (in many cases memberOf is also used in connection with Authorization).

Analogies with passport connector with focus on an ADFS would need to be understood.

**Comment by OwenBrotherwood** [comment]
@brandwe 
certificatemixed is the first hit for https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/metadata.js?#L88-L90

**Comment by OwenBrotherwood** [comment]
@brandwe 
I used a cert and a identityProviderUrl, and obtained a non-forms based login dialog.
callback problem needs work, as indicated in other issue, ie a check with my local friendly MS ADFS guy as to what parameter is in the url that should callback.

Please note: 
One problem at a time (ie ensure callback to /login/callback) but I have one nasty result by guessing: altering post /login/callback to post /  
Possible version issue with the expectation of v2 by the node_modules for the reply.

**Comment by OwenBrotherwood** [comment]
@ambahk 
I want to check SAML Tracer in my environment, so I will post experiences in this comment (also with reedits of this comment as I gain experience to if I am able to use it in my environment)

**Comment by ambahk** [comment]
@OwenBrotherwood thanks in advance for your kind sharing :)

**Comment by OwenBrotherwood** [comment]
@brandwe 
Looks like our "standard" internal ADSF is returns version 1.1 and the libraries in this package expect version 2.0.
This is a BIG issue if this is correct.
The README.md indicates "tested" and this can be reasonably assumed "by Microsoft".
What is tested?
- is this a azure centric solution or are the references to internal ADSF to be taken seriously?

The above sounds like a hard tone: sorry in advance, let's just get the issue sorted and placed in some flow. 
I will continue to check my findings and ensure that I have even more knowledge than I had first as I had expected a bit of plug and pray but the learning curve just went vertical.

**Comment by OwenBrotherwood** [comment]
@brandwe 
http://blogs.technet.com/b/askpfeplat/archive/2014/11/03/adfs-deep-dive-comparing-ws-fed-saml-and-oauth-protocols.aspx
WSFED 1.1
SAML: 2.0

Investigate configuring SAML on internal ADSF
Rework the README.md's

**Comment by brandwe** [comment]
We do not test against ADFS. We target Azure AD. ADFS, because it is a server product, necessarily lags behind the cloud. I doubt you'll see us support 1.x for Passport.js unfortunately, but I'm not certain what the status is of SAML or WS-FED support in 1.x. 

As far as WS-Fed vs. SAML vs. OpenID Connect. We have lots of customers using WS-Fed that come from Microsoft and SAML was the previous industry standard. We now have support for OpenID Connect on the server side but I don't have OpenID Connect working yet as part of this Passport platform. We don't give guidance on which is best as developers must decide based on their existing infrastructure. If targeting AzureAD alone, from developer perspective it should be transparent enough they don't care.

We've discussed this pull request and we will take it assuming it solves your problem. It sounds like from the above you still are having issues with ADFS 1.1 and SAML?

**Comment by polita** [comment]
@brandwe Please move this to the samples repo.
