### ISSUE TITLE
logoutUrl and loginCallback do not seem to work

### ISSUE THREAD

**Issue by Petah** [AzureAD/passport-azure-ad#26]
logoutUrl and loginCallback do not seem to work

The login/logout process seems to go trough alright, but the browser is not redirected back to the right place.

**Comment by brandwe** [comment]
Do you have the correct replyURL set up in Azure portal? The redirect should go to wherever you specified the replyURL to be. This is separate from Login URL.

**Comment by OwenBrotherwood** [comment]
@brandwe 
Using method from other post to obtain ADFS (non azure) standart browser (non-form) login prompt, I too have just hit the wrong callback. 
Doc issue? I need to reread the doc to see if the requirements of what the node world has to tell the MS ADFS world is clear ie. the set of values one has to agree on in order to get to and past the login and land at callback.

**Comment by brandwe** [comment]
We may have a fix. Awaiting the response to see if the finder wants to submit a PR to get credit :-)

**Comment by Petah** [comment]
Sorry, not using this anymore.

**Comment by brandwe** [comment]
What are you using instead if you don't mind me asking?>

**Comment by brandwe** [comment]
Fixed.
