### ISSUE TITLE
multiple scope is not working

### ISSUE THREAD

**Issue by gurusamy** [AzureAD/passport-azure-ad#286]
I have given multiple scope. But it is taking only "read your profile"
[ 'openid',
      'profile',
      'offline_access',
      'https://outlook.office.com/mail',
      'https://outlook.office.com/mail.readwrite',
      'https://outlook.office.com/calendars.readwrite',
      'https://outlook.office.com/contacts.readwrite',
      'https://outlook.office.com/tasks.readwrite' ]

**Comment by lovemaths** [comment]
@gurusamy what do you mean by "taking only read your profile"? Could you give more details?

**Comment by gurusamy** [comment]
In authentication consent scree, i could see only "read your profile" consent only. I want to access email, calendar in offline using refresh token. So how can i access email api and calendar api in offline using acces_token. Can you please check attached consent screen
![screen shot 2017-03-16 at 10 23 07 am](https://cloud.githubusercontent.com/assets/497632/24009725/1662026e-0a33-11e7-9daa-693156e650dc.png)

**Comment by lovemaths** [comment]
@gurusamy I tried to use the scope you provided, but I got "scope is not valid" error page from AAD v2 endpoint. When I replace the 'https://outlook.office.com' with 'https://graph.microsoft.com' in all the scopes, I do get the consent page ( see the screen shot).

What is the identityMetadata you are using in your application?

```
scope: ['profile', 'offline_access', 'https://graph.microsoft.com/mail.read',
  'https://graph.microsoft.com/mail.readwrite', 'https://graph.microsoft.com/calendars.readwrite', 
  'https://graph.microsoft.com/contacts.readwrite', 'https://graph.microsoft.com/tasks.readwrite']
```

![scope](https://cloud.githubusercontent.com/assets/6593843/24011340/c38b013a-0a37-11e7-8cd6-f5f0163836ff.png)

**Comment by gurusamy** [comment]
Hi Thank you for the response.. I am still getting the same consent screen. This the redirect url which has correct scope. Am i missing something?
https://login.microsoftonline.com/1b2401c7-7588-442fdfsdds-9bc1-09658da91816/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fopenid%2Freturn&response_type=code%20id_token&response_mode=form_post&client_id=ffc04bd5-844d-45b5-ba23-5271280ce2f8&state=CUSTOMdLI%2FqpbWY%2BTTAYGQq2Xq5q2ppPczAIb2my_state&nonce=1nzjYA8Zq%2Bc1qnpKsBjKUR%2Fr%2F4jc7WL3&resource=https%3A%2F%2Fgraph.windows.net&scope=profile%20offline_access%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.readwrite%20https%3A%2F%2Fgraph.microsoft.com%2Fcalendars.readwrite%20https%3A%2F%2Fgraph.microsoft.com%2Fcontacts.readwrite%20https%3A%2F%2Fgraph.microsoft.com%2Ftasks.readwrite%20openid&x-client-SKU=passport-azure-ad&x-client-Ver=3.0.5

**Comment by lovemaths** [comment]
@gurusamy You are using v1 endpoint, resource should be provided in the 'resource' parameter instead of 'scope'. In your request, you specified resource=https://graph.windows.net, so the access_token is for https://graph.windows.net. In your case all values in scope except 'openid profile' are not recognized by v1 so they will be ignored.

I think you might want to use v2 endpoint. One difference is: v1 you put resource in 'resource' parameter but v2 you put resource in 'scope' parameter. 

First register your app in https://apps.dev.microsoft.com/, and add the Microsoft Graph Permissions you want. Then in your config.js, change identityMetadata to "https://login.microsoftonline.com/<my_tenant_name>.onmicrosoft.com/v2.0/.well-known/openid-configuration", change scope to what I used. In passport.authenticate, remove 'resourceURL'. 

You should be able to achieve the same result as I do.

**Comment by lovemaths** [comment]
@gurusamy Please reopen the issue if the problem persists. Closing the issue. Thanks.
