### ISSUE TITLE
Access token lifetime

### ISSUE THREAD

**Issue by szarouski** [AzureAD/passport-azure-ad#325]
Hi, it would be great to be able to control access token lifetime via configuration. It seems not possible via this library yet, so please consider this issue as a feature request.

Thank you.

**Comment by lovemaths** [comment]
@szarouski There is nothing this library can do to configure token lifetime since this is controlled by Azure AD. You can configure token lifetime in Azure AD following [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes). I haven't personally tried it, hopefully it works for me.

**Comment by szarouski** [comment]
@lovemaths, thank you. I saw this article, just thought it could be possible in future. For now I'll close this ticket. Thanks again.
