### ISSUE TITLE
v3.0.7 BearerStrartegy throws scope is not found in token

### ISSUE THREAD

**Issue by chookie** [AzureAD/passport-azure-ad#327]
v3.0.6 works ok but v3.0.7 will not validate the token.

error
```
authentication failed due to: In Strategy.prototype.jwtVerify: scope is not found in token
```

endpoint
```
  app.use(`/${config.path}/graphql`,
    passport.authenticate('oauth-bearer'),
    GraphQLHTTP({
      schema: realSchema,
      graphiql: false,
      formatError: formatError({ config }),
    }));
```
setup
```
  passport.use(new BearerStrategy(bc,
    (token, done) => {
      return done(null, token);
    }
  ));
```

**Comment by lovemaths** [comment]
@chookie I think in your bearer strategy configuration, you provided `scope` option. v3.0.6 doesn't support this option, so this option doesn't do anything. In v3.0.7, we introduced `scope` option and added scope validation, so if this option is set, we validate the scope claim (`scp`) in token using the `scope` value provided. 

Since the token you are using has no scope value, simply remove the `scope` option in bearer strategy configuration, and it should work with v3.0.7.

**Comment by lovemaths** [comment]
@chookie Closing this issue. Please let me know if the solution doesn't work for you. Thank you.

**Comment by chookie** [comment]
@lovemaths Thank you I will check it out

**Comment by chookie** [comment]
Yes that worked thanks

**Comment by sureshkodur** [comment]
@lovemaths , That worked for me. Thanks a lot. You saved my time.
