### ISSUE TITLE
Session free auth flow

### ISSUE THREAD

**Issue by ErrorPro** [AzureAD/passport-azure-ad#356]
Hi, is there any docs or an example of session free auth?

Following the current docs doesn't help me at all.

I went through all the code base and I only saw logic around cookie is to parse it down to tuple, and later build a tuple and store it to res.cookie.

Maybe I understand it wrong but what I want to achieve is:

My app redirects user to azure login page, then azure redirects request back to my server where I get all info in strategy callback and passport.aad is being add to cookie, after that I redirect user back to my app and I can see passport.aad in browser's cookies. That's cool. But later when I want to call /me endpoint which is protected by `passport.authenticate('azuread-openidconnect', { session: false, response: res })` passport redirects me back to azure login page. 

My question is why? I got the cookie stored at client-side and it gets passed to all requests.

Thanks.

**Comment by lovemaths** [comment]
@ErrorPro Here is some background that helps.

(1) how passport.js keeps user signed in?

When user logs in for the first time, user enters username and password, then AAD returns an id_token. Passport.js extracts `user` info from id_token, and saves it in session.
For the subsequent request, passport.js sees the `user` object in session, so it says hey you are already logged in.
If you set `session: false`, then passport.js won't save `user` in session, so user will have to log in every time. This is usually used for web api. 
Passport-azure-ad is just a plugin of passport.js framework. This plugin has to store `state` and `nonce` values etc somewhere, people can either save them in session or cookie. By using cookie in passport-azure-ad, we can only achieve that passport-azure-ad plugin doesn't use session. 

(2) For the web farm case, if you use cookie for passport-azure-ad, it will work. The reason is that once user is logged in, user will have a cookie from AAD in their browser. If user is routed to a machine which doesn't have the user in session, `passport.authenticate` will initialiate the login flow, but since user already has a cookie from AAD, AAD will return the id_token without asking for the username and password. To the user, there won't be any difference.

(3) If you want session free completely. You have to store everything to cookie. You can try [cookie-session](https://github.com/expressjs/cookie-session). This way you basically store your session in cookies.

**Comment by ErrorPro** [comment]
@lovemaths Thank you for your response.
