### ISSUE TITLE
jwt token validation and session time out

### ISSUE THREAD

**Issue by satyareddy12** [AzureAD/passport-azure-ad#361]
Hi, i am implementing node app by using passport azure ad to get the tokens from azure and validate the token after receiving them. but i am facing some issues while validating the token. Library was taking default audience and issuer values  from token for validation including with the aud & issuer values we pass in config file in below function in oidcstrategy.js file.
verify id_token signature and claims
  return jwt.verify(id_token, PEMkey, optionsToValidate, (err, jwtClaims) => {

so the problem is when we pass a incorrect issuer in config and ask library to validate then it's still giving result as token is valid, in this case the expected result should be token is invalid. but it is getting default issuer from jwt token so it is giving me token is valid.

and one more issue i am facing is when the token gets expired lets us say in 60 minutes , in general the user session has to get new token from azure to continue the session .
but it is not happening , even after 60min the token get expire still it allows me to continue the session.

can you help me with the above 2 issues.

**Comment by lovemaths** [comment]
@satyareddy12 

(1) if you are using tenant specific endpoint for identity metadata url (something like https://login.microsoftonline.com/xx.....xx/.... or https://login.microsoftonline.com/xxx.onmicrosoft.com/...), then we will check the issuer in jwt token against the issuer provided in the metadata, if this fails, we check the issuer provided by you.

if you are using common endpoint (https://login.microsoftonline.com/common/...), then we will only use the issuer provided by you.

So the solution is to use the common endpoint for identity metadata.

(2) the whole purpose of passport framework is to keep you logged in. When we first get the jwt token, we will extract user information from the token and store it in node server session. You are logged in as long as you have the session in your node server, you don't need the token any more. 

If you want to destroy the session, you can call req.logout(), or you can set expiration in your session middleware (like express-session).

**Comment by satyareddy12** [comment]
thanks for quick response,
1)how about the audience validation, i am facing the same issue with audience too , it is getting default aud from token ,in addition to the audience value i pass in config file.
2)will it check the expiration of the token too by default ?
3) how long will be the session will be any specific time period and if it does so then the actual token issued by azure will be valid only for 60 min and after that library has to get new token or refresh token in the background to continue the session , this is how library has to work if i am correct. previously i use adal.js for react , and adal 4j for java to get token and maintain the session by getting new token or refresh token once the token gets expired.

**Comment by lovemaths** [comment]
@satyareddy12 
1) For OidcStrategy, we don't take any audience values provided by the user. The audience in the id_token must be (or contains) the client id, otherwise we will reject the token.
2) Library only validates id_token. Access token is opaque to the user, only the resource server knows how to validate it. Also access token is not necessarily a jwt (for instance, the access token for graph api on v2 endpoint, there is no way for any library to validate it).
3) Library will validate the expiration of id_token.
4) The session is between web browser and your node server, the time totally depends on how you set up your session middleware. You can set up the cookie expiration time in your session middleware, for example, [see here](https://github.com/AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS/blob/master/app.js#L157).
This library works differently from adal.js and adal4j. This library is only a plugin of passport.js framework. For passport.js framework in general, the login is solely based on the session between browser and your node server, as long as you have an user object saved in node server session, you are logged in. It doesn't need to maintain a valid id_token like adal.js and adal4j. When we get the id_token for the first time, we validate the token (expiration, issuer, audience, signature, etc), extract the user info from token, and save it into node server session. For the subsequent request, we only need to see if there is user info in node server session, and we don't need to talk to AAD anymore unless user info is not found.
This library basically only cares about id_token, since it is all we need for login purpose. 
For access token and refresh token, you will get access token and refresh token when you log in for the first time. If access token is expired, you can
4.1) write your code to refresh it (using adal-node), or 
4.2) simply call passport.authenticate to get new id_token, new access token and new refresh token. User won't need to enter username and password, since the session between browser and AAD is valid for a long time, maybe many days.

**Comment by satyareddy12** [comment]
thanks for your quick response and detail explanation about the library, above explanation helps a lot to understand about the library.
thanks once again!
