### ISSUE TITLE
use popup instead of redirect

### ISSUE THREAD

**Issue by jsve** [AzureAD/passport-azure-ad#386]
When logging in the user is redirected to login.microsoftonline.com. Some other libraries allow the use of a popup instead (https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Login-methods). Is this possible with passport as well?

**Comment by pkanher617** [comment]
@jsve passport is a Node.js framework, not a Javascript framework, and Node.js does not currently support opening a popup from the server side because there is no guarantee that the auth url is opened in a browser. You can do this by opening the url in a popup from the front-end code, but not from a passport app.
