### ISSUE TITLE
How can I deal with Conditional Access

### ISSUE THREAD

**Issue by MarkusFeldmann** [AzureAD/passport-azure-ad#394]
Hi
I created an Azure App that stopped working as soon as Conditional Access was activated, is there a way to get this to work with passport-azure-ad without completely rewriting it?

The problem is that when I got a first token lets say for the graph api that did not need CA/MFA then the app wants to aquire another one for sharepoint an error is sent "interaction_required". Because this happens on the server side I am not really sure how to best deal with it. Is there an easy way to deal with this in the api? 

Followup: I was able to make it work better to some extent, by first requesting a resource token for a resource that needs MFA due to CA when coming from an unmanaged device, so the following tokens will get delivered. I am not sure though what will happen if I have non MFA tokens then re-login from an unmanaged device. (This won't be the normal case, but I got a lot of users, the'll find a way for sure :-) )

Is there any good way to handle this, the problem is I ask for tokens after signin, what means: The DOM has been done with when the following tokens will be requested, how would expressjs/nodejs tell someone that they need to do something, like acknowledging a call,...
 
thanks a lot for any advice
Markus

**Comment by danieldobalian** [comment]
Hi Markus, 

There's a recommended pattern for this flow, and some future improvements that should make it easier. 

In terms of what you can do now, the error you get should contain a `claims` parameter. This is state that represents the policy from Conditional Access that needs to be fulfilled. Your API/Service should issue a HTTP 403 back to the client with this parameter. The client can then pass it into a new request to Azure AD (the ADAL libraries have a special overload exactly for this, otherwise you just add it as a query string). The end user will then have the opportunity to fulfill the delta between their current session and what's needed for the policy.

Happy to setup time and chat about the scenario and share some ideas for improving this scenario. My email is dadobali @[my_employer.com].  
 
We do have a doc on this scenario that may also help: https://docs.microsoft.com/en-us/azure/active-directory/develop/conditional-access-dev-guide

**Comment by pkanher617** [comment]
Closing for now. If there are further questions please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose).
