### ISSUE TITLE
Why is client secret required?

### ISSUE THREAD

**Issue by arynaq** [AzureAD/passport-azure-ad#407]
https://tools.ietf.org/html/rfc6749#section-4.2

Does not mention client_secret as a requirement for implicit flow for public clients.
I am guessing this is because we want to be able to silently refresh tokens?

In which case it would be great if that was optional and not locked in by code (if it isn't I would love to know how this can be configured).

**Comment by navyasric** [comment]
@arynaq The passport-azure-ad library is designed for auth flows in server side web apps built using Node.js. It uses the OIDC and OAuth 2.0 [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) and requires a client secret since it is a web app.
If you are looking for a library that performs the implicit flow on client side JS in a web browser, please take a look at the [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) library.
