### ISSUE TITLE
multi-resource refresh token support?

### ISSUE THREAD

**Issue by jccaulfield** [AzureAD/passport-azure-ad#408]
I need to get tokens to allow access to multiple (2) resources, but can't figure out how to make it work.

I found this document [Refresh Tokens for Mutliple Resources](https://docs.microsoft.com/en-us/previous-versions/azure/dn645538(v=azure.100)) which describes the process: use grant_type="refresh_token" and pass the refresh token along with the new resource to access, but it doesn't seem to be supported and I'm not sure where to start to add it. 

Is there an easy way to support this, or another way to get authorization tokens for multiple resources with a single sign-on? Thanks!

**Comment by pkanher617** [comment]
This is supported in the [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#oauth20-grant-types-supported). You can check the refresh token grant relevant sections in the docs for more info on usage. The only difference is that instead of sending resources, you will send scopes for the relevant resource. You can see our sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/refresh-token) for more info. Closing for now, please open an issue in the repo [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) if you are having issues.
