### ISSUE TITLE
OIDCStrategy policyName should be part of identityMetadata url

### ISSUE THREAD

**Issue by przemos** [AzureAD/passport-azure-ad#418]
Hi,

I have had a couple of days playing with this library. What struck me at the beginning was that OIDCStrategy requires policyName as a separate parameter. In fact, for B2C policyName is an integral part of metadata url. Metadata url for B2C as it is defined now i.e. https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/v2.0/.well-known/openid-configuration does not make any sense - it leads to 404.

Moreover, I am not sure why policy is required as a query param for the route initialising auth code flow. 

First, 
```
  // for B2C, we must have policy
  if (self._options.isB2C && !params.policy)
    return next(new Error('In collectInfoFromReq: policy is missing'));
```

imposes policy passed as a param to concat it with identityMetadata url in the end:
```
  if (self._options.isB2C)
    metadataUrl = metadataUrl.concat(`&p=${params.policy}`);
```

It is too complicated. Metadata url must be an authoritative source of information on Authorization Endpoint and there is currently no need to code  as above :)

**Comment by flyboarder** [comment]
Current version is clearly broken, either this should be a query param as to by customizable on request, or should be updated to use the policyName param.

**Comment by olarotseyi** [comment]
Were you able to solve this issue? I am having a similar issue, I cannot proceed to the api requiring authentication as my app keeps redirecting me to the login in page after my user is signed in

**Comment by buzziam** [comment]
In my case (my testing is cursory - **YMMV**), I'm supporting both BearerStrategy(`oauth-bearer`) *and*  OIDCStrategy(`azuread-openidconnect`). In the `azuread-openidconnect` case, I found that:
1. _not_ setting `isB2C` as an option sent to the ctor **yields successful results** 
1. _setting_ `isB2C` for the `oauth-bearer` strategy is required

Also - the query parameters for the `identityMetadata` URLs must be set differently for both cases:
1. for `azure-openidconnect` - a `p` query parameter (with value set to policyName) is required on the URL used for the `identityMetadata` config option
1. for `oauth-bearer` - you cannot add the `p` query param because the required `policyName` config option is required and is added automatically to the `identityMetadata` URL. If the parameter occurs twice (which should be considered valid w/r/t URLs) - `oauth-bearer` will not work.

**Comment by flyboarder** [comment]
we switched to using grant-js instead of passport to work around these issues. There are still some problems using the grant-js oauth provider but they are easier to work with.

**Comment by pkanher617** [comment]
This will be addressed in the upcoming version of the middleware library. You can track the progress of this [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). Closing for now.
