### ISSUE TITLE
Get "Unable to fetch metadata: Error: unable to verify the first certificate"

### ISSUE THREAD

**Issue by mithun-daa** [AzureAD/passport-azure-ad#77]
I am using `passport-azure-ad` to talk to a local instance of my (Idenity Server)[https://github.com/IdentityServer/IdentityServer3]. Will this module work only with Azure when using the OIDCStrategy?
![image](https://cloud.githubusercontent.com/assets/852171/11996937/878fbc52-aa34-11e5-9abf-1e0c7df70925.png)

**Comment by brandwe** [comment]
Well, i've only tested it with Azure as that's my focus at Microsoft :-) However my code should be generic enough. What I think is happening is it's hitting the metadata endpoint and not finding the cert where it expects. You can easily look at the code (in `metadata.js`) and see where it tries to grab the cert in the `waterfall()` and change the code. Since this only supports Azure we won't take that code change ourselves, but it might be good for others that want to use your server if you want to keep a fork out there.

**Comment by mithun-daa** [comment]
Turns out that it was because of the self signed cert. As a temporary workaround I set the following env variable:
````
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
````

That helped me get past that error but I ran into another error way within a dependency:
![image](https://cloud.githubusercontent.com/assets/852171/12020115/1ce6cc76-ad3e-11e5-84c0-b0deb32bdddd.png)

Any ideas? The `waiting` variable is `{}` in `callback_filler.js` file.

**Comment by brandwe** [comment]
I have never run in to this. Can you maybe try the passport-azure-ad in /dev and see if you still have the issue?

**Comment by mithun-daa** [comment]
Looks like switching the branch helped. Now the OIDC Provider redirects back to my callback but the `verify` callback or the serializer/deserialzer never get called.

**Comment by mithun-daa** [comment]
Never mind - as soon as I set `skipUserProfile` to true it started working. Thanks a bunch for you prompt responses.
